<a href="https://colab.research.google.com/github/Joshbolus/CPSC-349-Project/blob/main/Joshua_bolus_wrangling_tidy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CPSC 375 Classwork - Data wrangling - Joins and Tidy Data

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ProfAvery/cpsc375-classwork/blob/main/wrangling-tidy.ipynb)

- *Manager*:
- *Recorder*:
- *Presenter*:
- *Timekeeper*:

*Note*: On Google Colab, run the following code cell to download the `cpsc375` module before trying to `import`:

In [1]:
!mkdir -p ./cpsc375 && wget --quiet --timestamping https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/cpsc375/__init__.py --output-document=./cpsc375/__init__.py

In [2]:
from cpsc375 import *

## Part 1 - Slide 10

In [3]:
band_members = pd.DataFrame(
    {"Name": ["Mick", "John", "Paul"], "Band": ["Stones", "Beatles", "Beatles"]}
)

band_instruments = pd.DataFrame(
    {"Name": ["John", "Paul", "Keith"], "Plays": ["guitar", "bass", "guitar"]}
)

<table>
<tr>
  <th>
    <code>band_members_4rows</code> (left table)
  </th>
  <th>
    <code>band_instruments_4rows</code> (right table)
  </th>
</tr>
<tr>
  <td>

| Name | Band    |
|------|---------|
| Mick | Stones  |
| John | Beatles |
| Paul | Beatles |
| Paul | Wings   |

  </td>
  <td>

| Name  | Plays  |
|-------|--------|
| John  | guitar |
| Paul  | bass   |
| Keith | guitar |
| Paul  | vocals |

  </td>
</tr>
</table>

Calculate the different joins for these two tables.

First, do them by hand

Then, confirm your results with code

In [4]:
band_members_4rows = pd.concat([
  band_members,
  pd.DataFrame(dict(Name=["Paul"], Band=["Wings"]))
], ignore_index=True)

## Part 2 - Slide 28

Write code to "tidy" this dataset

In [5]:
grades = pd.DataFrame(
  dict(
    CWID=(1234567, 2356902, 5005667),
    NAME=("Mary", "Lee", "Elena"),
    CPSC120=(3, 4, pd.NA),
    CPSC121=(3.3, 3, 2),
    CPSC131=(3, 4, 3.7),
    MATH338=(3, pd.NA, 3.3),
  )
)

In [6]:
(
  grades
  .melt(
      id_vars=['CWID', 'NAME'],
      # value_vars=[''],
      var_name='COURSE',
      value_name='GRADE'
  )
  .sort_values('CWID')
)

       CWID   NAME   COURSE GRADE
0   1234567   Mary  CPSC120     3
3   1234567   Mary  CPSC121   3.3
6   1234567   Mary  CPSC131   3.0
9   1234567   Mary  MATH338     3
7   2356902    Lee  CPSC131   4.0
4   2356902    Lee  CPSC121   3.0
10  2356902    Lee  MATH338  <NA>
1   2356902    Lee  CPSC120     4
5   5005667  Elena  CPSC121   2.0
2   5005667  Elena  CPSC120  <NA>
8   5005667  Elena  CPSC131   3.7
11  5005667  Elena  MATH338   3.3

## Part 3 - Slide 33

`language_diversity.csv` contains data on the diversity of languages in different countries and other parameters.

In [7]:
language_diversity = pd.read_csv(
    "https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/datasets/language_diversity.csv"
)

Calculate:
 * The total number of languages in every continent

In [8]:
(
    language_diversity
    .query('Measurement == "Langs"')
    .groupby('Continent')
    .agg({'Value': 'sum'})

)

            Value
Continent
Africa     2513.0
Americas    877.0
Asia       1977.0
Oceania    1273.0

* Add a new variable that shows for every country its population density
  (PopulationDensity=Population/Area)

Hint: **First** convert to tidy data using `pivot()`

In [9]:
(
    language_diversity
    .pivot(
        index=['Continent', 'Country'],
        columns='Measurement',
        values='Value'
    )
    .reset_index()
    .rename_axis(None, columns=1)
)

Measurement,Continent,Country,Area,Langs,MGS,Population,Stations,Std
0,Africa,Algeria,2381741.0,18.0,6.60,25660.0,102.0,2.29
1,Africa,Angola,1246700.0,42.0,6.22,10303.0,50.0,1.87
2,Africa,Benin,112622.0,52.0,7.14,4889.0,7.0,0.99
3,Africa,Botswana,581730.0,27.0,4.60,1348.0,10.0,1.69
4,Africa,Burkina Faso,274000.0,75.0,5.17,9242.0,6.0,1.07
...,...,...,...,...,...,...,...,...
69,Asia,Yemen,527968.0,6.0,0.00,12302.0,2.0,0.00
70,Oceania,Australia,7713364.0,234.0,6.00,17336.0,134.0,4.17
71,Oceania,Papua New Guinea,462840.0,862.0,10.88,3772.0,8.0,1.96
72,Oceania,Solomon Islands,28896.0,66.0,12.00,3301.0,1.0,0.00
73,Oceania,Vanuatu,12189.0,111.0,12.00,163.0,4.0,0.00

Original dataset:
 * <https://github.com/jvcasillas/untidydata#language_diversity>
 * <https://www.researchgate.net/publication/222464328_Explaining_Global_Patterns_of_Language_Diversity>

## Part 4 - Slide 36

`horse_racing.csv` contains data related to horse racing licensing in New York.

In [10]:
horse_racing = pd.read_csv(
    "https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/datasets/horse_racing.csv"
)

Transform the dataset such that:

* The License column is split into two:
  - `LicenseOrReceipt`: a categorical variable with two categories "License" and "Receipt"
  - `Number`: numeric column with the license/receipt number

In [11]:
horse_racing[['LicenseOrReceipt', 'Number']] = horse_racing.License.str.split(' # ', expand=True)
horse_racing.Number = horse_racing.Number.astype(int)
horse_racing.head()

SyntaxError: invalid syntax (4122980329.py, line 1)

* The `Expires` column is split into three:
  - `Year`, `Month`, `Day` (all integers)

In [10]:
(
    horse_racing
    .assign
)


) Original dataset: <https://data.ny.gov/Government-Finance/Horse-Racing-Licensing/cz9u-yj7m/data>

## Part 5 - Slide 37

Consider the dataset: `billboard`

> Hint: convert to tidy data **first**

1. Show for each track, how many weeks it spent on the chart

2. List tracks in decreasing order of number of weeks spent on the chart

3. Show for each track, its top rank

4. List tracks in increasing order of its top rank

5. Show for each artist, their top rank

6. List artists in increasing order of their top rank

7. List tracks that only spent one week in the charts

8. List tracks that only spent one week in the charts along with its artist